// Code generated by scripts/genmodules.go; DO NOT EDIT.

export interface ModuleManifest {
    id: string;
    displayName: string;
    version: string;
    enabledByDefault: boolean;
    frontend?: {
        entry: string;
        nav?: { title: string; href: string; icon: string }[];
        routes?: { path: string; viewKey: string; title: string }[];
    };
}

export const modules: ModuleManifest[] = [];

export const loadEntry = (id: string) => {
    return Promise.reject(new Error("Unknown module: " + id));
};
